services:
  - type: web
    name: datasage-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        value: 6253434262524328352838362
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: FRONTEND_URL
        value: https://datasage-ui.vercel.app
      - key: DATASET_TTL_MINUTES
        value: 30
      - key: MAX_SAVED_VERSIONS
        value: 5
      - key: SUPABASE_URL
        value: https://yonjwlnjlihhsalcfmzg.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: datasage-db
          property: connectionString

databases:
  - name: datasage-db
    plan: free
    databaseName: datasage
    user: datasage
